<a href="https://colab.research.google.com/github/Shakilgithub20/Basic-Computer-Vision-ML-DL-NLP/blob/main/ann_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
from sklearn.datasets import make_circles

# Make 1000 examples
n_samples = 1000

# Create circles
X, y = make_circles(n_samples, 
                    noise=0.03, 
                    random_state=42)

In [14]:
# Check out the features
X


array([[ 0.75424625,  0.23148074],
       [-0.75615888,  0.15325888],
       [-0.81539193,  0.17328203],
       ...,
       [-0.13690036, -0.81001183],
       [ 0.67036156, -0.76750154],
       [ 0.28105665,  0.96382443]])

In [15]:
# See the first 10 labels
y[:10]

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [16]:
# Make dataframe of features and labels
import pandas as pd
circles = pd.DataFrame({"X0":X[:, 0], "X1":X[:, 1], "label":y})
circles.head()

X0      X1  label
0  0.7542  0.2315      1
1 -0.7562  0.1533      1
2 -0.8154  0.1733      1
3 -0.3937  0.6929      1
4  0.4422 -0.8967      0

In [17]:
# Check out the different labels
circles.label.value_counts()

1    500
0    500
Name: label, dtype: int64

In [18]:
# View the first example of features and labels
X[0], y[0]

(array([0.75424625, 0.23148074]), 1)

# **Model-1**

In [20]:
import tensorflow as tf
# Set random seed
tf.random.set_seed(42)

# 1. Create the model using the Sequential API
model_1 = tf.keras.Sequential([
  tf.keras.layers.Dense(1)
])

# 2. Compile the model
model_1.compile(loss=tf.keras.losses.BinaryCrossentropy(), # binary since we are working with 2 clases (0 & 1)
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['accuracy'])

# 3. Fit the model
model_1.fit(X, y, epochs=5)

Epoch 1/5
32/32 [==============================] - 1s 1ms/step - loss: 2.8544 - accuracy: 0.4600
Epoch 2/5
32/32 [==============================] - 0s 2ms/step - loss: 0.7131 - accuracy: 0.5430
Epoch 3/5
32/32 [==============================] - 0s 2ms/step - loss: 0.6973 - accuracy: 0.5090
Epoch 4/5
32/32 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5010
Epoch 5/5
32/32 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.4830


In [21]:
# Train our model for longer (more chances to look at the data)
model_1.fit(X, y, epochs=200, verbose=0) # set verbose=0 to remove training updates
model_1.evaluate(X, y)

32/32 [==============================] - 0s 1ms/step - loss: 0.6935 - accuracy: 0.5000


[0.6934831142425537, 0.5]

# **Model-2**

In [23]:
# Set random seed
tf.random.set_seed(42)

# 1. Create the model (same as model_1 but with an extra layer)
model_2 = tf.keras.Sequential([
  tf.keras.layers.Dense(1), # add an extra layer
  tf.keras.layers.Dense(1) 
])

# 2. Compile the model
model_2.compile(loss=tf.keras.losses.BinaryCrossentropy(),
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['accuracy'])

# 3. Fit the model
model_2.fit(X, y, epochs=100, verbose=0) # set verbose=0 to make the output print less

In [24]:
# Evaluate the model
model_2.evaluate(X, y)

32/32 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.5000


[0.6933314800262451, 0.5]

# **Model-3**

In [25]:
# Set random seed
tf.random.set_seed(42)

# 1. Create the model (this time 3 layers)
model_3 = tf.keras.Sequential([
  # Before TensorFlow 2.7.0
  # tf.keras.layers.Dense(100), # add 100 dense neurons

  ## After TensorFlow 2.7.0 ##
  tf.keras.layers.Dense(100, input_shape=(None, 1)), # add 100 dense neurons with input_shape defined (None, 1) = look at 1 sample at a time
  tf.keras.layers.Dense(10), # add another layer with 10 neurons
  tf.keras.layers.Dense(1)
])

# 2. Compile the model
model_3.compile(loss=tf.keras.losses.BinaryCrossentropy(),
                optimizer=tf.keras.optimizers.Adam(), # use Adam instead of SGD
                metrics=['accuracy'])

# 3. Fit the model
model_3.fit(X, y, epochs=100, verbose=0) # fit for 100 passes of the data

In [26]:
model_3.evaluate(X, y)

32/32 [==============================] - 0s 2ms/step - loss: 0.6939 - accuracy: 0.5000


[0.6939496994018555, 0.5]

In [35]:
from keras.utils import np_utils
from keras.models import Sequential 
from keras.layers import Dense, Dropout, BatchNormalization, Flatten
from tensorflow import keras
from keras.datasets import mnist

In [36]:
# the data, shuffled and split between train and test sets 
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [37]:
# if we observe the above matrix each cell is having a value between 0-255
# before we move to apply machine learning algorithms lets try to normalize the data
# X => (X - Xmin)/(Xmax-Xmin) = X/255

X_train = X_train/255
X_test = X_test/255

In [38]:
X_train_o = X_train
X_test_o = X_test

X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# print the final input shape ready for training
print("Train matrix shape", X_train.shape)
print("Test matrix shape", X_test.shape)

Train matrix shape (60000, 784)
Test matrix shape (10000, 784)


In [39]:
# here we are having a class number for each image
print("Class label of first image :", y_train[0])

# lets convert this into a 10 dimensional vector
# ex: consider an image is 5 convert it into 5 => [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
# this conversion needed for MLPs 

Y_train = np_utils.to_categorical(y_train, 10) 
Y_test = np_utils.to_categorical(y_test, 10)

print("After converting the output into a vector : ",Y_train[0])

Class label of first image : 5
After converting the output into a vector :  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


# **M-1**

In [49]:
# Define the Model
model = None
model = Sequential()

model.add(Dense(10, input_dim=784, activation='softmax'))
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
# Fit the Model

# model.fit(X, y,  epochs=10)
model.fit(X_train, Y_train, epochs=100, verbose=0)

In [50]:
model.evaluate(X_train, Y_train)

1875/1875 [==============================] - 3s 1ms/step - loss: 0.2192 - accuracy: 0.9394


[0.2192203551530838, 0.9393666386604309]

# **M-2**

In [51]:
# Define the Model

model_sigmoid = None
model_sigmoid = Sequential()

model_sigmoid.add(Dense(512, input_dim=784, activation='sigmoid', kernel_initializer='glorot_normal'))
model_sigmoid.add(Dropout(0.3))

model_sigmoid.add(Dense(128, activation='sigmoid', kernel_initializer='glorot_normal'))
model_sigmoid.add(Dropout(0.3))

model_sigmoid.add(Dense(10, activation='softmax'))

In [52]:
# Compile the Model

model_sigmoid.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
# Fit the Model

model_sigmoid.fit(X_train, Y_train, batch_size=128, epochs=100,verbose=0) #ep=10 acc: 0.9925

In [53]:
model_sigmoid.evaluate(X_train, Y_train) 

1875/1875 [==============================] - 6s 3ms/step - loss: 1.1862e-04 - accuracy: 1.0000


[0.00011861775419674814, 0.9999833106994629]

# **M-3**

In [54]:
# Define the Model

model_relu = None
model_relu = Sequential()

# FC - 512
model_relu.add(Dense(512, input_dim=784, activation='relu', kernel_initializer='he_normal'))
model_relu.add(BatchNormalization())
model_relu.add(Dropout(0.3))

# FC - 128
model_relu.add(Dense(128, activation='relu', kernel_initializer='he_normal'))
model_relu.add(BatchNormalization())
model_relu.add(Dropout(0.3))

# FC - 10
model_relu.add(Dense(10, activation='softmax'))

# Compile the Model

model_relu.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Fit the Model

model_relu.fit(X_train, Y_train, batch_size=128, epochs=100,verbose=0) #ep=10 accuracy: 0.9955

In [62]:
model_relu.evaluate(X_train, Y_train)

1875/1875 [==============================] - 6s 3ms/step - loss: 1.8219e-04 - accuracy: 0.9999


[0.0001821913756430149, 0.9999499917030334]